name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    types: [labeled, synchronize]
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: [ "ubuntu-latest" ]
    if: github.event.label.name == 'build-image' || contains(github.event.pull_request.labels.*.name, 'build-image') || (github.event_name == 'push' && github.ref == 'refs/heads/main')

    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=start::$(date +'%s')"
        shell: bash

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Sleep for 60 minutes
        run: sleep 3600
        shell: bash